version: '3'

services:

  website-gateway-cache:
    container_name: website-gateway-cache
    image: redis:3.2.7
    restart: always
    ports:
      - "6379:6379"
    environment:
      - BOOTIFUL_MICRO_PIZZA_ENV=dev
      - TZ=Europe/London
    volumes:
      - /etc/localtime:/etc/localtime

  config-service:
    container_name: config-service
    build: services/config-service
    restart: always
    ports:
      - "8888:8888"
    environment:
      - BOOTIFUL_MICRO_PIZZA_ENV=dev
      - TZ=Europe/London
    volumes:
      - /etc/localtime:/etc/localtime

  registry-service-1:
    container_name: registry-service-1
    build: services/registry-service
    restart: always
    ports:
      - "8761:8761"
    environment:
      - BOOTIFUL_MICRO_PIZZA_ENV=dev
      - TZ=Europe/London
      - EUREKA_HOST_PORT=8761
      - EUREKA_HOST_NAME=registry-service-1
    volumes:
      - /etc/localtime:/etc/localtime

  api-gateway:
    container_name: api-gateway
    build: services/api-gateway
    restart: always
    ports:
      - "9060:9060"
    environment:
      - BOOTIFUL_MICRO_PIZZA_ENV=dev
      - TZ=Europe/London
    volumes:
      - /etc/localtime:/etc/localtime

  inventory-service:
    container_name: inventory-service
    build: services/inventory-service
    restart: always
    ports:
      - "9004:9004"
    environment:
      - BOOTIFUL_MICRO_PIZZA_ENV=dev
      - TZ=Europe/London
      - OAUTH2_PUBLIC_KEY=-----BEGIN PUBLIC KEY-----MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA0HQ8LznbLwn5t1WJX3yifpnYvneTOW6eXpj76sePBopoM8/j4JjGSXBJ7DYwHik1szocEKRoSNcdlfgXkiGFd1IHpRCUm9NAfw2+Pde87IzprAWnokt0AVnAhaXK7aa2L7gMD0bTrujiLp+GYdy7U5m+9fhWbOWhWJGvwD1g6KwymDPHRmjH3cO3XM3OQncqAYSNPCW/eKuSv7KNROeZdBkx7wVRVU+Z3GACshxNFUVj3qE7F3FdmPKsHXy3uzJclqaqMp5gzwUblmTqbHajChnDUaKXCgxz7Yi2NVC/STD8PIrijOxYlHfX9kjsk7qYYrtuH2V2xvKkmsO1f6mSvQIDAQAB-----END PUBLIC KEY-----
    volumes:
      - /etc/localtime:/etc/localtime

  order-service:
    container_name: order-service
    build: services/order-service
    restart: always
    ports:
      - "9008:9008"
    environment:
      - BOOTIFUL_MICRO_PIZZA_ENV=dev
      - TZ=Europe/London
      - OAUTH2_PUBLIC_KEY=-----BEGIN PUBLIC KEY-----MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA0HQ8LznbLwn5t1WJX3yifpnYvneTOW6eXpj76sePBopoM8/j4JjGSXBJ7DYwHik1szocEKRoSNcdlfgXkiGFd1IHpRCUm9NAfw2+Pde87IzprAWnokt0AVnAhaXK7aa2L7gMD0bTrujiLp+GYdy7U5m+9fhWbOWhWJGvwD1g6KwymDPHRmjH3cO3XM3OQncqAYSNPCW/eKuSv7KNROeZdBkx7wVRVU+Z3GACshxNFUVj3qE7F3FdmPKsHXy3uzJclqaqMp5gzwUblmTqbHajChnDUaKXCgxz7Yi2NVC/STD8PIrijOxYlHfX9kjsk7qYYrtuH2V2xvKkmsO1f6mSvQIDAQAB-----END PUBLIC KEY-----
    volumes:
      - /etc/localtime:/etc/localtime

  account-service:
    container_name: account-service
    build: services/account-service
    restart: always
    ports:
      - "9005:9005"
    environment:
      - BOOTIFUL_MICRO_PIZZA_ENV=dev
      - TZ=Europe/London
      - OAUTH2_PUBLIC_KEY=-----BEGIN PUBLIC KEY-----MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA0HQ8LznbLwn5t1WJX3yifpnYvneTOW6eXpj76sePBopoM8/j4JjGSXBJ7DYwHik1szocEKRoSNcdlfgXkiGFd1IHpRCUm9NAfw2+Pde87IzprAWnokt0AVnAhaXK7aa2L7gMD0bTrujiLp+GYdy7U5m+9fhWbOWhWJGvwD1g6KwymDPHRmjH3cO3XM3OQncqAYSNPCW/eKuSv7KNROeZdBkx7wVRVU+Z3GACshxNFUVj3qE7F3FdmPKsHXy3uzJclqaqMp5gzwUblmTqbHajChnDUaKXCgxz7Yi2NVC/STD8PIrijOxYlHfX9kjsk7qYYrtuH2V2xvKkmsO1f6mSvQIDAQAB-----END PUBLIC KEY-----
    volumes:
      - /etc/localtime:/etc/localtime

  website-api-gateway:
    container_name: website-api-gateway
    build: services/website-api-gateway
    restart: always
    ports:
      - "8000:8000"
    environment:
      - BOOTIFUL_MICRO_PIZZA_ENV=dev
      - TZ=Europe/London
      - OAUTH2_PUBLIC_KEY=-----BEGIN PUBLIC KEY-----MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA0HQ8LznbLwn5t1WJX3yifpnYvneTOW6eXpj76sePBopoM8/j4JjGSXBJ7DYwHik1szocEKRoSNcdlfgXkiGFd1IHpRCUm9NAfw2+Pde87IzprAWnokt0AVnAhaXK7aa2L7gMD0bTrujiLp+GYdy7U5m+9fhWbOWhWJGvwD1g6KwymDPHRmjH3cO3XM3OQncqAYSNPCW/eKuSv7KNROeZdBkx7wVRVU+Z3GACshxNFUVj3qE7F3FdmPKsHXy3uzJclqaqMp5gzwUblmTqbHajChnDUaKXCgxz7Yi2NVC/STD8PIrijOxYlHfX9kjsk7qYYrtuH2V2xvKkmsO1f6mSvQIDAQAB-----END PUBLIC KEY-----
    volumes:
      - /etc/localtime:/etc/localtime
